name: Compile and Test

permissions:
  contents: read
  pull-requests: read

on:
  push:
    paths-ignore:
      - "*.md"
    branches:
      - main
  pull_request:
    paths-ignore:
      - "*.md"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Update platform's packages database
        run: sudo apt-get update

      - name: Install platform tools
        run: sudo apt-get install -y build-essential yamllint 

      - name: Lint YAML files
        run: find . -type f -name "*.yml" -exec yamllint {} \;

      - name: Checkout project
        uses: actions/checkout@v4

      - name: Compile
        run: make

      - name: Test
        run: ./test.sh
