name: Compile and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install platform tools
        run: sudo apt-get install -y build-essential

      - name: Compile program
        run: make

      - name: Run test
        run: |
          if [ -f ./slacksecchk ] && [ -x ./slacksecchk ]; then
            echo "Test passed."
          else
            echo "Test failed."
            exit 1
          fi